### ISSUE TITLE
Locol WG Monthly: Mar 20th @ 6pm GMT / 10am PST

### ISSUE THREAD

**Issue by momack2** [ipfs/local-offline-collab#11]
We will be holding our next working group monthly on March 20th - feel free to add agenda items you'd like to discuss in the notes doc: https://docs.google.com/document/d/1Mol6epw0sbj5FqS6akD-X5KJkGF0MwsOZQ5t1ehOGiM/edit#!

Zoom: https://protocol.zoom.us/j/9049149336

**Comment by momack2** [comment]
We will hopefully have @nicopace with us on Mar 20 to talk more about his research on the dweb in global south communities. 

Some new folks in the ipfs community who might be interested include @creationix @jorropo @onggunhao @gozala. Looking forward to also seeing our regular attendees like @raulk @terichadbourne @whyrusleeping @djdv @jedahan @jimpick and others.

**Comment by momack2** [comment]
Reminder to everyone that this is happening tomorrow at 10am PST! Looking forward to learning from @nicopace about his global south research and also hearing any updates from others working in the space - maybe @gozala re the PWAs over IPFS work that @jimpick mentioned last month, or @jorropo about his prototypes for p2p app downloads in his bandwidth-constrained school.

**Comment by Gozala** [comment]
@momack2 I wish I could attend, so I could  share details of work I’ve being doing, but sadly it overlaps with a meeting at work that I can’t skip.
Could you please cc me on next one, I’ll make sure to make it then
