### ISSUE TITLE
Locol WG Monthly: Apr 17th @ 5pm GMT / 10am PST

### ISSUE THREAD

**Issue by momack2** [ipfs/local-offline-collab#13]
We will be holding our next working group monthly on April 17th - feel free to add agenda items you'd like to discuss in the notes doc: https://docs.google.com/document/d/1Mol6epw0sbj5FqS6akD-X5KJkGF0MwsOZQ5t1ehOGiM/edit#heading=h.1m8wal85c4s6

### Agenda so far:
**(Momack2, 5-10 mins)[ offline package manager concept](https://github.com/ipfs/package-managers/issues/37)**
- Ability to cache needed packages offline by default
- Ability to seed cached packages to local peers

**(Jonathan, 5-10 minutes) Distributed web of care teaser**
- Issues with Dat
- Issues with bridging network interfaces / routing
- Issues with provisioning ubiquiti hardware

[**ADD MORE**](https://docs.google.com/document/d/1Mol6epw0sbj5FqS6akD-X5KJkGF0MwsOZQ5t1ehOGiM/edit#heading=h.1m8wal85c4s6)

Zoom: https://protocol.zoom.us/j/9049149336

Everyone is welcome: @creationix @Jorropo @onggunhao @Gozala @raulk @terichadbourne @whyrusleeping @djdv @jedahan @jimpick and others.

**Comment by Gozala** [comment]
@momack2 I can do another brief demo of [lunet](https://github.com/gozala/lunet) (did one during browser WG call while back) if that is [still interesting](https://github.com/ipfs/local-offline-collab/issues/11#issuecomment-474715921).

**Comment by creationix** [comment]
Oh wow, I just now saw this notification.  Looks like it was interesting.
