### ISSUE TITLE
Locol SIG Monthly: Wed, Aug 21 @ 10am PDT | 1pm EDT | 5pm UTC

### ISSUE THREAD

**Issue by terichadbourne** [ipfs/local-offline-collab#19]
We will be holding our next SIG (Special Interest Group) monthly on Wednesday, August 21 - feel free to add agenda items you'd like to discuss in the notes doc: https://docs.google.com/document/d/1Mol6epw0sbj5FqS6akD-X5KJkGF0MwsOZQ5t1ehOGiM/edit

Agenda so far:

- Demo by Yiannis Psaras (@yiannisbot) of [Data Hop](http://datahop.network/), which uses Bluetooth low energy and WiFi direct together to enable file sharing between devices irrespective of network
- Insights from DWeb Camp
- ADD MORE!

Zoom: https://protocol.zoom.us/j/884541689

Everyone is welcome: @creationix @Jorropo @onggunhao @Gozala @raulk @terichadbourne @whyrusleeping @djdv @jedahan @jimpick @nicopace @raulk @codynhat @yiannisbot @momack2 @JustMaier @vrortvedt @autonome @parkan and others.

**Comment by terichadbourne** [comment]
Just a reminder that our next Local & Offline Collaboration SIG (Special Interest Group) call takes place this Wednesday, August 21 at 10am Pacific / 1pm Eastern / 5pm UTC. Hope to see you there!

**Agenda so far:**
- Demo by Yiannis Psaras (@yiannisbot) of [Data Hop](http://datahop.network/), which uses Bluetooth low energy and WiFi direct together to enable file sharing between devices irrespective of network
- Insights from DWeb Camp
- Upcoming Offline Camp Oregon (Sept 27-30)
- ADD MORE in our agenda/notes doc: https://docs.google.com/document/d/1Mol6epw0sbj5FqS6akD-X5KJkGF0MwsOZQ5t1ehOGiM/edit

Zoom: https://protocol.zoom.us/j/884541689 

Everyone is welcome: @creationix @Jorropo @onggunhao @Gozala @raulk @terichadbourne @whyrusleeping @djdv @jedahan @jimpick @nicopace @raulk @codynhat @yiannisbot @momack2 @JustMaier @vrortvedt @autonome @parkan and others.

**Comment by nicopace** [comment]
Hi all,
I would also like to share with you all a project that I am supporting, with the Nam Community in Namibia, and indigenous collectives in Brazil, India and New Zealand for oral story sharing that uses DWeb technologies... hope we have time for that! See you all in a bit,

**Comment by terichadbourne** [comment]
Thanks to all who attended today's call, and especially to @yiannisbot for telling us about the Data Hop project and to @nicopace and Nicola Bidwell for sharing their experiences create audio social networks for the San people of Namibia. It was also great to hear some reflections on DWeb camp from @parkan @momack2 & @nicopace. 

If you missed today's call, you can [watch the video](https://youtu.be/72IHALtKjVI) or check out our [meeting notes](https://docs.google.com/document/d/1Mol6epw0sbj5FqS6akD-X5KJkGF0MwsOZQ5t1ehOGiM/edit?usp=sharing).

[![image](https://user-images.githubusercontent.com/19171465/63460257-2b8c6a00-c424-11e9-8d7f-4a753288d2e1.png)](https://youtu.be/72IHALtKjVI)

Hope to see you at next month's call on Wednesday, September 18. Watch the [new event issue](https://github.com/ipfs/local-offline-collab/issues/21) for updates, and please let me know if you'd like to share or demo your project!
