### ISSUE TITLE
Locol SIG Monthly: Wed, Oct 16 @ 10am PDT | 1pm EDT | 5pm UTC

### ISSUE THREAD

**Issue by terichadbourne** [ipfs/local-offline-collab#22]
Mark your calendars! 

The next monthly call of the **IPFS Local Offline Collaboration SIG** (Special Interest Group) will take place on **Wednesday, October 16 at 10am PDT | 1pm EDT | 5pm UTC**.  
- [See when this is in your local timezone](https://everytimezone.com/s/8ed51482)
- View this event on the [IPFS Community Calendar](https://calendar.google.com/calendar/embed?src=ipfs.io_eal36ugu5e75s207gfjcu0ae84@group.calendar.google.com&pli=1)
- [Join us on Zoom](https://protocol.zoom.us/j/884541689) when the time comes

Do you have a project in the Offline First or local networking space that you'd like to share with us? Please let me know so we can add you to our [agenda](https://docs.google.com/document/d/1Mol6epw0sbj5FqS6akD-X5KJkGF0MwsOZQ5t1ehOGiM/edit)! 

Our agenda so far: 
- Attendees of [**Offline Camp**](http://offlinefirst.org/camp) (coming up Sept 27-30 in Grants Pass, Oregon) will share their favorite discussion highlights on the intersection of Offline First and DWeb use cases, challenges, and solutions. (There are still tickets and scholarships available if you'd like to join the event.)
- YOUR ITEM HERE!

Want to catch up on past conversations? Review our past [meeting notes](https://docs.google.com/document/d/1Mol6epw0sbj5FqS6akD-X5KJkGF0MwsOZQ5t1ehOGiM/edit) or check out our [video archive](https://www.youtube.com/playlist?list=PLuhRWgmPaHtSfSw2L-McV5w9nGoM5QzLO), with lots of awesome demos. 

Everyone is welcome: @creationix @Jorropo @onggunhao @Gozala @raulk @terichadbourne @whyrusleeping @djdv @jedahan @jimpick @nicopace @raulk @codynhat @yiannisbot @momack2 @JustMaier @vrortvedt @autonome @parkan @jessicaschilling
@nicopace @canadaduane @arkadiy @monteslu @arecvlohe @davidhernandeze @meiqimichelle and others

**Comment by terichadbourne** [comment]
Looking forward to seeing everyone for the monthly call of the **IPFS Local Offline Collaboration SIG** (Special Interest Group)  **tomorrow, Wednesday, October 16 at 10am PDT | 1pm EDT | 5pm UTC**.  
- [See when this is in your local timezone](https://everytimezone.com/s/8ed51482)
- View this event on the [IPFS Community Calendar](https://calendar.google.com/calendar/embed?src=ipfs.io_eal36ugu5e75s207gfjcu0ae84@group.calendar.google.com&pli=1)
- [Join us on Zoom](https://protocol.zoom.us/j/884541689) when the time comes

Some of the dweb enthusiasts who attended [Offline Camp Oregon](http://offlinefirst.org/camp) last month will be on hand to share highlights of the conversations they found most interesting. 

Do you have a project in the Offline First or local networking space that you'd like to share with us? Please let me know so we can add you to our [agenda](https://docs.google.com/document/d/1Mol6epw0sbj5FqS6akD-X5KJkGF0MwsOZQ5t1ehOGiM/edit)!

**Comment by nicopace** [comment]
I am not going to be able to attend to this call, as I will be preparing for a workshop on Community Networks with [LibreRouter.org](https://LibreRouter.org) ... will share in future calls about it, that I will do in Mexico, Tanzania, Lebanon and India in the following two months.

**Comment by terichadbourne** [comment]
That sounds like an awesome project @nicopace! Any chance you'd be available to share more about it on our November 20 call? Best of luck with the project!

**Comment by nicopace** [comment]
will try!

**Comment by terichadbourne** [comment]
Thanks to all who attended today's call, and especially to @mburns for sharing some of his insights from [Offline Camp](http://offlinefirst.org/camp), @autonome for introducing us to [Physicians for Human Rights](https://phr.org/), and @lidel for his updates on IPFS work in progress related to offline use cases in web browsers. 

A number of our camp alumni couldn't make it today due to scheduling conflicts, so we're happy to circle back to any discussions on later calls, or follow up as related articles are posted in the [Offline Camp Medium publication](https://medium.com/offline-camp). Just let us know what you'd like to chat about further! 

If you missed today's call, you can [watch the video](https://youtu.be/ekyn35r2zTE) or check out our [meeting notes](https://docs.google.com/document/d/1Mol6epw0sbj5FqS6akD-X5KJkGF0MwsOZQ5t1ehOGiM/edit?usp=sharing). 

[![image](https://user-images.githubusercontent.com/19171465/66952889-79d87680-f02b-11e9-8b2c-7cae125de958.png)](https://youtu.be/ekyn35r2zTE)

Next month's call will take place a week earlier than usual, on Wednesday, November 13. Watch the [new event issue](https://github.com/ipfs/local-offline-collab/issues/23) for updates, and please let me know if you'd like to share or demo your project!

**Comment by arecvlohe** [comment]
Does IPFS have a Slack workspace?

**Comment by terichadbourne** [comment]
@arecvlohe In my experience, people in the IPFS community tend more to IRC or discussion forums. 

> Get in touch with other members of the IPFS community who are building tools on top of IPFS or even helping to build IPFS itself! You can ask questions, discuss new ideas, or get support for problems at https://discuss.ipfs.io, but you can also [hop on IRC](https://docs.ipfs.io/community/irc) for a quick chat.

If you scroll down to the Community section in the nav on the [IPFS docs site](https://docs.ipfs.io/#community) you can find links to a number of other communication spaces and social accounts. 

For the broader Offline First community there's a Slack workspace which you can sign up for at http://offlinefirst.org/chat
