### ISSUE TITLE
Locol SIG Monthly: Wed, Nov 13 @ 10am PST | 1pm EST | 6pm UTC

### ISSUE THREAD

**Issue by terichadbourne** [ipfs/local-offline-collab#23]
Mark your calendars! (We're veering off of our typical 3rd-Wednesday-of-the-month schedule for this one due to a scheduling conflict, and the change in daylight savings is a bit confusing, so please take note!)

The next monthly call of the **IPFS Local Offline Collaboration SIG** (Special Interest Group) will take place on **Wednesday, November 13 at 10am PST | 1pm EST | 6pm UTC**.  (**_**Note the time change in UTC**_**; still at the same time for most of our attendees!) 
- [See when this is in your local timezone](https://everytimezone.com/s/8620e54a)
- View this event on the [IPFS Community Calendar](https://calendar.google.com/calendar/embed?src=ipfs.io_eal36ugu5e75s207gfjcu0ae84@group.calendar.google.com&pli=1)
- [Join us on Zoom](https://protocol.zoom.us/j/884541689) when the time comes

Do you have a project in the Offline First or local networking space that you'd like to share with us? Please let me know so we can add you to our [agenda](https://docs.google.com/document/d/1Mol6epw0sbj5FqS6akD-X5KJkGF0MwsOZQ5t1ehOGiM/edit)! 

Our tentative agenda so far: 
- @lidel demo (5-10m) ideas behind [ipfs-shipyard/cohosting](https://github.com/ipfs-shipyard/cohosting) using  the [ipfs-cohost](https://github.com/ipfs-shipyard/ipfs-cohost) command-line tool
- @nicopace  you've mentioned potential topics recently; please let me know if this date is convenient for you! 

Want to catch up on past conversations? Review our past [meeting notes](https://docs.google.com/document/d/1Mol6epw0sbj5FqS6akD-X5KJkGF0MwsOZQ5t1ehOGiM/edit) or check out our [video archive](https://www.youtube.com/playlist?list=PLuhRWgmPaHtSfSw2L-McV5w9nGoM5QzLO), with lots of awesome demos. 

Everyone is welcome: @creationix @Jorropo @onggunhao @Gozala @raulk @terichadbourne @whyrusleeping @djdv @jedahan @jimpick @nicopace @raulk @yiannisbot @momack2 @JustMaier @vrortvedt @autonome @parkan@nicopace @canadaduane @arkadiy @monteslu @arecvlohe @davidhernandeze @meiqimichelle  and others

**Comment by terichadbourne** [comment]
Our next monthly meeting of the IPFS Local Offline Collaboration SIG is scheduled for next **Wednesday, November 13 at 10am PST | 1pm EST | 6pm UTC** ([see when this is in your local timezone](https://everytimezone.com/s/8620e54a)).

@nicopace & @lidel, you've both suggested topics for demos/discussions recently. Would this be a good time for either of you to share. Suggestions from others are also welcome!

**Comment by lidel** [comment]
I won't have bandwidth to prepare, but can demo (5-10m) ideas behind [ipfs-shipyard/cohosting](https://github.com/ipfs-shipyard/cohosting) using  the [ipfs-cohost](https://github.com/ipfs-shipyard/ipfs-cohost) command-line tool.

**Comment by nicopace** [comment]
I won't have mental bandwidth either for this one... december will be different I believe.

**Comment by terichadbourne** [comment]
No worries, @nicopace. I'll check in with you as the December meeting approaches.

**Comment by terichadbourne** [comment]
Looking forward to seeing all those who are available on the **IPFS Local Offline Collaboration SIG** (Special Interest Group) call **today, November 13 at 10am PST | 1pm EST | 6pm UTC**.  (**_**Note the time change in UTC**_**; still at the same time for most of our attendees!) 
- [See when this is in your local timezone](https://everytimezone.com/s/8620e54a)
- View this event on the [IPFS Community Calendar](https://calendar.google.com/calendar/embed?src=ipfs.io_eal36ugu5e75s207gfjcu0ae84@group.calendar.google.com&pli=1)
- [Join us on Zoom](https://protocol.zoom.us/j/884541689) when the time comes

Today we'll have a demo from @lidel on  the ideas behind [ipfs-shipyard/cohosting](https://github.com/ipfs-shipyard/cohosting) using  the [ipfs-cohost](https://github.com/ipfs-shipyard/ipfs-cohost) command-line tool. 🎉

We have space for more discussions on the [agenda](https://docs.google.com/document/d/1Mol6epw0sbj5FqS6akD-X5KJkGF0MwsOZQ5t1ehOGiM/edit), so please feel free to come with other topics in mind. We're excited to hear about other projects in the Offline First or local networking space!
