### ISSUE TITLE
First Local Offline Collab WG Monthly: Dec 19th @ 8pm GMT / 12pm PST 

### ISSUE THREAD

**Issue by momack2** [ipfs/local-offline-collab#4]
We will be holding our first focus area meet-up next week on Dec 19th right after the IPFS Q1 OKR call. We'll move to an earlier time (~6pm GMT) in the future to accommodate more folks in earlier time zones. This will be a kickoff for anyone interested in discussing these topics more - we'll do intros and align on what we want to get out of these syncs. Feel free to add agenda items you'd like to discuss in **[the notes doc](https://docs.google.com/document/d/1Mol6epw0sbj5FqS6akD-X5KJkGF0MwsOZQ5t1ehOGiM/edit#)**!

Zoom: https://protocol.zoom.us/j/9049149336

Offline-interested folks, you should come: @djdv @pgte @terichadbourne @raulk @hannahhoward @mikeal @mgoelzer

Mobile-interested folks - happy to discuss those needs too: @fsdiogo @PedroMiguelSS @victorb

**Comment by terichadbourne** [comment]
@momack2 Are you planning on 30 minutes or an hour for this one? 

Will there be a calendar invite or are you trying to keep it off of the public community calendar? 

If you get to (or are at) a point where you'd like involvement from non-employee-types, you might get some interest from sharing the invitation in the Offline First Slack team.

**Comment by momack2** [comment]
It’s on the IPFS Community calendar and is open to anyone interested in
participating - I’ll make a call for attendees on the offline-first slack!
We’ve booked an hour, but if we don’t use it we’ll adjust future meetings.

**Comment by pgte** [comment]
@momack2 I'm super interested, but unfortunately at that time I can't attend..
I'll be watching the videos and notes though! :)

**Comment by momack2** [comment]
@pgte we'll move future meetings to ~6pm GMT on Wednesdays - will that be a better time you can attend?

**Comment by pgte** [comment]
@momack2 yes, I can attend at that time :)

**Comment by momack2** [comment]
Thanks to everyone for the great first meeting! We have a ton of [notes here](https://docs.google.com/document/d/1Mol6epw0sbj5FqS6akD-X5KJkGF0MwsOZQ5t1ehOGiM/edit#
) and a [recording of our chat](https://drive.google.com/file/d/1wUIcoB_krzSgSKL1WkRsmnSlgagBLK3s/view?usp=sharing) for those who weren't able to attend synchronously. Looking forward to our next sync in January!
