### ISSUE TITLE
2019 Q1 Locol WG OKRs

### ISSUE THREAD

**Issue by momack2** [ipfs/local-offline-collab#5]
## Local Offline Collab OKRs
We may be a fledgling working group, but it's time for us to work on our OKRs for Q1 2019! We'll use this issue for proposals and discussions of OKRs the next quarter. Since we are new, we don't have Q4 OKRs to grade or retrospect on, but we can reference the [research plan](https://github.com/ipfs/local-offline-collab/blob/master/Research_Plan.md) to spell out some of what we want to achieve next year. 

ref: https://github.com/ipfs/team-mgmt/issues/792

- [x] 2019 Q1 OKRs Open Planning (this thread)
- [ ] Move 2019 Q1 OKRs to [2019 Q1 OKRs Spreadsheet](https://docs.google.com/spreadsheets/d/1BtOfd7s9oYO5iKsIorCpsm4QuQoIsoZzSz7GItE-9ys/edit#gid=1720716278)

**Comment by momack2** [comment]
### Main goals for Q1:
- Init research! 
  - Gather knowledge - interviews/docs, partner feedback, community needs
  - Coalesce early findings - state of the union
- Find and form relationships with external communities to support and learn from
- Form IPFS Locol WG community, structure, and charter

**Comment by terichadbourne** [comment]
I view [Offline Camp](http://offlinefirst.org/camp/) as a great opportunity for research where we can learn a lot about community needs. We don't have the next event scheduled yet, but it will likely be in Q2 so my logistical planning will start in Q1. (@mikeal suggested that this working group might be the right place for any OKRs related to my Offline Camp work to live.)

**Comment by momack2** [comment]
Awesome!! That's a great idea - very happy to document that work here and it ties nicely both with research and collaboration with other communities. =] I'll add that to the main repo page too.

**Comment by pgte** [comment]
@momack2 this is super!
We may have some learnings to share from yesterday's talk to the Textile dev team:
https://docs.google.com/document/d/12FfpBbouhBxr0VnyLg59RIGyPaR36zMVw5tCG0kbL3g/edit# where they talked about their work to support mobile offline for the Textile photos app.

**Comment by momack2** [comment]
Here's a first draft at WG OKRs - would love everyone's feedback/ideas to enhance them! @pgte, is there any room for collaboration with DDC Q1 priorities, or areas we can support you?

**O1: Form Locol team presence and community**
- KR: Establish regular team communication channels, forums, and team culture
- KR: Grow Locol community to 5+ monthly active contributors _(this could be a lowball - not sure yet)_
- KR: Increase IPFS Locol visibility and awareness with 3+ reference materials (videos, posts, etc) with over 50 views each

**O2: Init IPFS Local/Offline-First research**
- KR: Collect and synthesize existing knowledge (common paths, pain points, needs, best practices) from IPFS users
- KR: Perform census of offline/local-first tool space and create taxonomy of existing and potential collaborators
- KR: Draft IPFS Local/Offline-First state of the union documenting existing market, uses, pain points, and opportunities
- KR: Scope 2 Locol-driven work packages to support biggest pain points/opportunities evaluated so far

**O3: Engage with wider Local/Offline-First communities**
- KR: Plan Offline Camp 2019 _(@terichadbourne can you flesh this out? any other KRs to add?)_
- KR: Engage with 2 research organizations with insight into local/offline end-user needs
- KR: Form relationships with 2+ established players in the local/offline-first space and understand their strategy/best practices for achieving and sustaining impact

**Comment by momack2** [comment]
I (tentatively) plan to allocate 70% of my time to the Locol WG this quarter. With 11 weeks -> 55 days -> 440 hours - 60% of that = 264 hours for OKRs during the quarter - 184 of which I'll be spending on Locol tasks (aka 23 days). As captain I expect to be responsible for O1 and chunks of O2 and O3 - but would love others to pick up any threads that seem relevant!

**Comment by pgte** [comment]
@momack2 this is great, I'd be glad to help out with some research and / or census!

For DDC we have this KR named "KR1.9: Peer-base works well offline (depends on js-ipfs +internal tests and work)", which means that a collaboration can progress locally for nodes that start offline, become offline or that have intermittent and partial connectivity.

**Comment by terichadbourne** [comment]
@momack2 For the Offline Camp KR, how does this sound? (I want to ensure it's clear that Offline Camp is a third-party community event, not one run by Protocol Labs, which means we won't control any decision-making processes for it independently.)

_Set a date for the next Offline Camp (an external community event for the Offline First community), determine PL's desired sponsorship level, and begin logistical planning with co-organizers._

**Comment by momack2** [comment]
@pgte - I'd also be interested in talking more about crafting and disseminating design best practices for the offline/p2p world, since that seems like a common struggle for dapp builders on IPFS - adding a shared OKR for that to the offline sheet. =] Maybe I'll start attending the DDC weekly in 2019 to loop our work closer together?

> Set a date for the next Offline Camp (an external community event for the Offline First community), determine PL's desired sponsorship level, and begin logistical planning with co-organizers.

@terichadbourne - sounds good!  These are IPFS working group OKRs, so definitely no expectation of PL involvement here. I kept the owner clarification but dropped the relative PL language. =]

Moving all this to the sheet and adding priority, owners, and rephrasing as needed! Let's continue the conversation **[here](https://docs.google.com/spreadsheets/d/1BtOfd7s9oYO5iKsIorCpsm4QuQoIsoZzSz7GItE-9ys/edit#gid=427965902)**.

**Comment by pgte** [comment]
@pgte that would be great! :)

**Comment by terichadbourne** [comment]
@momack2 Your rewording in the Google Doc works for me!

**Comment by momack2** [comment]
Hey folks! Please take a quick look at our Q1 OKRs in the [public OKR sheet](https://docs.google.com/spreadsheets/d/1BtOfd7s9oYO5iKsIorCpsm4QuQoIsoZzSz7GItE-9ys/edit#gid=427965902) to make sure we're accounting for all the important work this quarter. I'm (hopefully) going to add a line about drafting an RFP for a p2p transport for libp2p since that will be a really valuable building block for future quarters.

**Comment by terichadbourne** [comment]
Looks good to me @momack2. As we discussed, I'll be happy to help you find homes for those "reference materials" in the Offline Camp or (soon-to-exist, name TBC) Protocol Medium publications as appopriate.

**Comment by momack2** [comment]
Closing this out to freeze our OKRs for the quarter. 🎉
