### ISSUE TITLE
Locol WG Monthly: Jan 23rd @ 6pm GMT / 10am PST

### ISSUE THREAD

**Issue by momack2** [ipfs/local-offline-collab#7]
We will be holding our first working group monthly of the new year on January 23rd - feel free to add agenda items you'd like to discuss in the notes doc: https://docs.google.com/document/d/1Mol6epw0sbj5FqS6akD-X5KJkGF0MwsOZQ5t1ehOGiM/edit#!

Zoom: https://protocol.zoom.us/j/9049149336

Offline-interested folks, you should come (note the earlier time!): @djdv @pgte @terichadbourne @raulk @hannahhoward @mikeal @mgoelzer - everyone is welcome!

**Comment by momack2** [comment]
Looking forward to seeing everyone in 10 minutes!

**Comment by momack2** [comment]
Great seeing everyone yesterday! As usual our [recording is online](https://drive.google.com/open?id=1WQugETUamyZj_vLF290PS14X8oB7RUGe), [meeting notes are up](https://docs.google.com/document/d/1Mol6epw0sbj5FqS6akD-X5KJkGF0MwsOZQ5t1ehOGiM/edit#), and we have a lot of great takeaways including [finalized Q1 OKRs](https://docs.google.com/spreadsheets/d/1BtOfd7s9oYO5iKsIorCpsm4QuQoIsoZzSz7GItE-9ys/edit?ts=5c2f3d49#gid=427965902)! See you all next month!

**Comment by pgte** [comment]
Unfortunately for me I could not attend this one ...
Thank you for posting the recording, though, I went through it and enjoyed the discussions, and I'm looking forward to participating in the next one!
